// <auto-generated />
using System;
using EbeddedApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations.Rls
{
    [DbContext(typeof(UserPbiRlsContext))]
    [Migration("20230307183423_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EbeddedApi.Models.UserPbiRls", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataUltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_ultimo_acesso");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmailContato")
                        .HasColumnType("text")
                        .HasColumnName("email_contato");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("empresa");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identificacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.Property<string>("Perfil")
                        .HasColumnType("text")
                        .HasColumnName("Perfil");

                    b.HasKey("Id");

                    b.ToTable("user_pbi_rels", (string)null);
                });

            modelBuilder.Entity("EbeddedApi.Models.UserVisions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("vision_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VisionId");

                    b.ToTable("user_visions", (string)null);
                });

            modelBuilder.Entity("EbeddedApi.Models.Vision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("visions", (string)null);
                });

            modelBuilder.Entity("EbeddedApi.Models.UserVisions", b =>
                {
                    b.HasOne("EbeddedApi.Models.UserPbiRls", null)
                        .WithMany("UserVisions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EbeddedApi.Models.Vision", "Vision")
                        .WithMany()
                        .HasForeignKey("VisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vision");
                });

            modelBuilder.Entity("EbeddedApi.Models.UserPbiRls", b =>
                {
                    b.Navigation("UserVisions");
                });
#pragma warning restore 612, 618
        }
    }
}
