export const icmsType = ['INTEGRAL', 'C/BENEFICIO', ' S/FECP']
export const products = [
  {
    description: ' DIESEL A S-10',
    value: 'd828b027-c66d-4f12-9e6c-f1ec0ca06bd1'
  },
  {
    description: ' DIESEL A S-500',
    value: '2a168639-e6f0-433f-8059-f6d90426c0e2'
  },
  {
    description: ' BIODIESEL B-10',
    value: 'caf3778c-3b35-40d4-bc6c-fe0851c987ee'
  }
]
export const produtos = [
  {
    description: 'DIESEL S-10',
    value: 'd828b027-c66d-4f12-9e6c-f1ec0ca06bd1'
  },
  {
    description: 'DIESEL S-500',
    value: '2a168639-e6f0-433f-8059-f6d90426c0e2'
  }
]
export const fornecedoresTypeMock = [
  { id: 0, type: '76 OIL' },
  { id: 1, type: 'ACOL' },
  { id: 2, type: 'AGILE' },
  { id: 3, type: 'ALCOOLBRAS' },
  { id: 4, type: 'ALCOOLPETRO' },
  { id: 5, type: 'ALESAT' },
  { id: 6, type: 'ALFA PETRÓLEO' },
  { id: 7, type: 'ALL' },
  { id: 8, type: 'ALLGREEN' },
  { id: 9, type: 'ALPES' },
  { id: 10, type: 'AMERICANOIL' },
  { id: 11, type: 'ARAGUAIA' },
  { id: 12, type: 'ARAPETRO' },
  { id: 13, type: 'ARKA' },
  { id: 14, type: 'ART PETRO' },
  { id: 15, type: 'ASPEN' },
  { id: 16, type: 'ASTER' },
  { id: 17, type: `ATEM'S` },
  { id: 18, type: 'ATLANTA' },
  { id: 19, type: 'ATLÂNTICA' },
  { id: 20, type: 'AZA' },
  { id: 21, type: 'BETUNEL' },
  { id: 22, type: 'BIOPETRO' },
  { id: 24, type: 'BIOPETRÓLEO' },
  { id: 25, type: 'BIOSTRATUM' },
  { id: 26, type: 'BIZUNGÃO' },
  { id: 27, type: 'BRASPETRO' },
  { id: 28, type: 'BV' },
  { id: 29, type: 'CARBOPETRO' },
  { id: 30, type: 'CENTRO OESTE' },
  { id: 31, type: 'CHARRUA' },
  { id: 32, type: 'CIAPETRO' },
  { id: 33, type: 'COPERCANA' },
  { id: 34, type: 'CRUZ DE MALTA' },
  { id: 35, type: 'D`MAIS' },
  { id: 36, type: 'DANPETRO' },
  { id: 37, type: 'DIBRAPE' },
  { id: 38, type: 'DIRECIONAL' },
  { id: 39, type: 'DISLUB' },
  { id: 40, type: 'DUVALE' },
  { id: 41, type: 'EASY PETRO' },
  { id: 42, type: 'ECO' },
  { id: 43, type: 'ECO BRASIL' },
  { id: 44, type: 'ECOLOGICA' },
  { id: 45, type: 'ECOMAT' },
  { id: 46, type: 'EQUADOR' },
  { id: 47, type: 'ESTRADA' },
  { id: 48, type: 'EVEREST' },
  { id: 49, type: 'FAN' },
  { id: 50, type: 'FEDERAL ENERGIA' },
  { id: 51, type: 'FÉLIX' },
  { id: 52, type: 'FERA' },
  { id: 53, type: 'FGC' },
  { id: 54, type: 'FLAG' },
  { id: 55, type: 'FLAGLER' },
  { id: 56, type: 'FLEX DISTRIBUORA' },
  { id: 57, type: 'FLEXPETRO' },
  { id: 58, type: 'GAZ PRIME' },
  { id: 59, type: 'GOL COMBUSTÍVEIS' },
  { id: 60, type: 'GP' },
  { id: 61, type: 'GRAN PETRO' },
  { id: 62, type: 'GREEN' },
  { id: 63, type: 'HORA' },
  { id: 64, type: 'IMPERIAL' },
  { id: 65, type: 'IMPERIO' },
  { id: 66, type: 'IPIRANGA' },
  { id: 67, type: 'ISABELLA' },
  { id: 68, type: 'J.R DISTRIBUORA' },
  { id: 69, type: 'JACAR' },
  { id: 70, type: 'LARCO' },
  { id: 71, type: 'LERPETRO' },
  { id: 72, type: 'MANGUINHOS' },
  { id: 73, type: 'MAR AZUL' },
  { id: 74, type: 'MAS' },
  { id: 75, type: 'MASUT DISTRIBUORA' },
  { id: 76, type: 'MAX DISTRIBUORA' },
  { id: 77, type: 'MAXSUL' },
  { id: 78, type: 'MAXXI' },
  { id: 79, type: 'MEG' },
  { id: 80, type: 'MINUANO' },
  { id: 81, type: 'MONTE CABRAL' },
  { id: 82, type: 'MONTEPETRO' },
  { id: 83, type: 'NOROESTE' },
  { id: 84, type: 'ON PETRO' },
  { id: 85, type: 'PARANAPANEMA' },
  { id: 86, type: 'PELIKANO' },
  { id: 87, type: 'PETRO AMAZON' },
  { id: 88, type: 'PETRO NORTE' },
  { id: 89, type: 'PETROALCOOL' },
  { id: 90, type: 'PETROBAHIA' },
  { id: 91, type: 'PETROBALL' },
  { id: 92, type: 'PETROEXPRESS' },
  { id: 93, type: 'PETROGOIAS' },
  { id: 94, type: 'PETROLUZ' },
  { id: 95, type: 'PETRONAC' },
  { id: 96, type: 'PETROQUALITY' },
  { id: 97, type: 'PETRORIENTE' },
  { id: 98, type: 'PETROSALVADOR' },
  { id: 99, type: 'PETROSERRA' },
  { id: 100, type: 'PETROSUL' },
  { id: 101, type: 'PETROTORQUE' },
  { id: 102, type: 'PETROWORLD' },
  { id: 103, type: 'PETROX DISTRIBUORA' },
  { id: 104, type: 'PETROZIL JC' },
  { id: 105, type: 'PHOENIX' },
  { id: 106, type: 'PODIUM' },
  { id: 107, type: 'PONTUAL' },
  { id: 108, type: 'POTENCIAL' },
  { id: 109, type: 'RAIZEN' },
  { id: 110, type: 'RAIZEN MIME' },
  { id: 111, type: 'RAVATO' },
  { id: 112, type: 'REALCOOL' },
  { id: 113, type: 'REDE SOL' },
  { id: 114, type: 'REDEPETRO' },
  { id: 115, type: 'REJAILE' },
  { id: 116, type: 'RIO BRANCO' },
  { id: 117, type: 'RM PETROLEO' },
  { id: 118, type: 'RODOIL' },
  { id: 119, type: 'RODOPETRO' },
  { id: 120, type: 'ROYAL FIC' },
  { id: 121, type: 'RUFF C.J.' },
  { id: 122, type: 'RUMOS' },
  { id: 123, type: 'RZD DISTRIBUORA' },
  { id: 124, type: 'SAARA' },
  { id: 125, type: 'SABBÁ' },
  { id: 126, type: 'SADA COMBUSTÍVEIS' },
  { id: 127, type: 'SAFRA' },
  { id: 128, type: 'SETTA DISTRIBUORA' },
  { id: 129, type: 'SIM DISTRIBUOR' },
  { id: 130, type: 'SIMARELLI' },
  { id: 131, type: 'SL' },
  { id: 132, type: 'SMALL' },
  { id: 133, type: 'SOLL' },
  { id: 134, type: 'SP' },
  { id: 135, type: 'SR BRASIL (EX-METRON)' },
  { id: 136, type: 'STANG' },
  { id: 137, type: 'START PETROLEO' },
  { id: 138, type: 'STOCK' },
  { id: 139, type: 'SUL COMBUSTÍVEIS' },
  { id: 140, type: 'SULPETRO' },
  { id: 141, type: 'TABOCAO' },
  { id: 142, type: 'TAG DISTRIBUORA' },
  { id: 143, type: 'TAURUS' },
  { id: 144, type: 'TDC DISTRIBUORA' },
  { id: 145, type: 'TEMAPE' },
  { id: 146, type: 'TERRA BRASIL' },
  { id: 147, type: 'TOBRAS' },
  { id: 148, type: 'TORRAO' },
  { id: 149, type: 'TOTALENERGIES' },
  { id: 150, type: 'TOWER' },
  { id: 151, type: 'TRANSO' },
  { id: 152, type: 'TRIANGULO' },
  { id: 153, type: 'UNI' },
  { id: 154, type: 'UNIBRASPE' },
  { id: 155, type: 'VAISHIA' },
  { id: 156, type: 'VETOR' },
  { id: 157, type: 'VIBRA ENERGIA (PETROBRAS)' },
  { id: 158, type: 'WALENDOWSKY' },
  { id: 159, type: 'WATT' },
  { id: 160, type: 'WEBPETRO' },
  { id: 161, type: 'WELLPETRO' }
]

export const productsTypeMock = [
  { id: 0, type: 'Diesel Comum' },
  { id: 1, type: 'BioDiesel' }
]

export const modTransportTypeMock = [
  { id: 0, type: 'CIF' },
  { id: 1, type: 'FOB' }
]
