// <auto-generated />
using System;
using EbeddedApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EbeddedApi.Migrations.TFA
{
    [DbContext(typeof(UserTFAContext))]
    [Migration("20220512034832_InitialMigrate")]
    partial class InitialMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EbeddedApi.Models.TFA.UserTFA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("TFASecretKey")
                        .HasColumnType("text")
                        .HasColumnName("tfa_secret_key");

                    b.Property<bool?>("TFASettedUp")
                        .HasColumnType("boolean")
                        .HasColumnName("tfa_setted_up");

                    b.HasKey("Id");

                    b.ToTable("user_tfa_configuration");
                });
#pragma warning restore 612, 618
        }
    }
}
